source/apps/clientes/urls.py
# Importaciones del sistema
from django.urls import path
from .views import *

app_name = "clientes"

urlpatterns = []

source/apps/mutual/urls.py
# Importaciones del sistema
from django.urls import path
from .views import *
app_name = "mutual"

urlpatterns = [
    
    path('crearMutual/',MutualCreateView.as_view(), name="mutual_crear"),
    path('mutuales/listado', MutualesListView.as_view(), name="listado_mutual"),
    path('mutuales/editar/<int:pk>', EditarMutal, name="editar_mutual"),

    path('declaracionjurada/crear/<str:accion>/', DeclaracionJuradaCreateView.as_view(), name="declaracion_jurada"),
    path('declaracionjurada/historialDeclarado',DeclaracionJuradaDeclaradoListView.as_view(), name="declaracion_jurada_declarado_listado"),
    
    path('declaracionjurada/leer',leerDeclaracionJurada , name="leer_declaracion_jurada"),
    path('verificar_todas_leidas/<int:periodo_pk>/', verificar_todas_leidas, name='verificar_declaraciones_todas_leidas'),

    path('declaracionjurada/historico',HistoricoView.as_view(), name="historico"),
    path('DeclaracionJurada/<int:pk>/', descargarDeclaracion, name="descargarDeclaracion"),
    path('DeclaracionJurada/archivo/<int:pk>/', descargarArchivo, name="descargarArchivo"),


    path('periodos/periodo/crear', PeriodoCreateView.as_view(), name="periodo_crear"),
    path('periodos/periodo/vigente', periodoVigenteDetalle , name="periodo_vigente_detalle"),
    path('periodos/periodo/vigente/<int:pk>/mutuales/nopresentaron', periodoVigenteMutualNoPresento , name="mutual_no_presento"),
    path('periodos/periodo/vigente/<int:pk>/finalizar', finalizarPeriodo , name="finalizar_periodo"),
    path('periodos/periodo/vigente/<int:pk>/finalizar_crear_nuevo', finalizarPeriodoCrearNuevo , name="finalizar_periodo_crear_nuevo"),
    
    path('periodos/periodo/<int:pk>/comprimir', comprimirPeriodo, name="comprimir_periodo"),
    
    path('periodos/periodo/descargar', seleccionarPeriodoComprimir, name="comprimir_archivos_periodo"),
    
    
    path('exito/', mutual_exito, name='mutual_exito'),
    path('prueba/', tu_vista, name='t_vista'),
    path('datos/', DetalleMutualView.as_view(), name='detalles_mimutual'),
    path('confirmacion/', ConfirmacionView.as_view(), name='confirmacion'),
    path('visualizar_errores/', VisualizarErroresView.as_view(), name='visualizarE'),
    path('msj_informativo/', MsjInformativo.as_view(), name='msj_info'),

]

source/mutualWeb/urls.py
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from mutualWeb.views import *
from .views import *
from mutualWeb import views



urlpatterns = [
    #PRIINCIPALES
    # path('', bienvenida , name='index'),
    path('', RedirectView.as_view(url='login/', permanent=False), name='index'),
    path('admin_manager_ministerio/', admin.site.urls),
    path('dashboard/', dashboard, name='dashboard'),

    #APLICACIONES
    path('dashboard/clientes/', include('apps.clientes.urls')),
    path('dashboard/mutual/', include('apps.mutual.urls')),
    path('dashboard/personas/', include('apps.personas.urls')),
    path('', include('apps.users.urls')),
    path('home/app_reportes/',include('apps.reportes.urls')),

    path("selectable/", include("selectable.urls")),
    path('buscar_mutuales/', views.buscar_mutuales, name='buscar_mutuales'),
    
    # para abir los manuales
    path('manual_usuario_mutual/', abrirManualMutual, name="pdf_manual_mutual"),
    path('manual_usuario_operativos/', abrirManualOperativos, name="pdf_manual_operativos"),
    path('manual_usuario_administrador/', abrirManualAdministrador, name="pdf_manual_administrador"),
]

handler404 = "mutualWeb.views.pagina_no_encontrada"

source/apps/clientes/models.py
from apps.personas.models import Rol
from django.db import models
from ..mutual.models import Mutual


class Cliente(Rol):
    TIPO = 2
    mutual = models.ForeignKey(Mutual, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.id} {self.mutual.cuit}"
    

Rol.register(Cliente)

source/apps/clientes/forms.py
from django import forms
from apps.personas.models import Persona
from django.core.exceptions import ValidationError
from django.contrib.auth.hashers import make_password
from utils.regularexpressions import alpha_validator, telefono_validator

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.translation import gettext as _

class RegistroUsuarioForm(UserCreationForm):
    nombre = forms.CharField(max_length=30, required=True, help_text=_("Obligatorio. Máximo 30 caracteres."))
    apellido = forms.CharField(max_length=30, required=True, help_text=_("Obligatorio. Máximo 30 caracteres."))
    telefono = forms.CharField(max_length=15, required=False, help_text=_("Opcional. Máximo 15 caracteres."))
    email = forms.EmailField(max_length=254, required=True, help_text=_("Obligatorio. Se requiere una dirección de correo electrónico válida."))

    username = forms.CharField(max_length=150, help_text=_("Obligatorio. 150 caracteres o menos. Solo letras, dígitos y @/./+/-/_."))

    password1 = forms.CharField(
        label=_("Contraseña"),
        strip=False,
        widget=forms.PasswordInput,
        help_text=_("Tu contraseña no puede ser demasiado similar a tu otra información personal. Debe contener al menos 8 caracteres. No puede ser una contraseña común. No puede ser completamente numérica."),
    )

    password2 = forms.CharField(
        label=_("Confirmación de contraseña"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=_("Ingresa la misma contraseña que antes, para verificación."),
    )

    class Meta:
        model = User
        fields = ('nombre', 'apellido', 'telefono', 'email', 'username', 'password1', 'password2')

class FormularioCliente(forms.ModelForm):
    contraseña = forms.CharField(max_length=50, widget=forms.PasswordInput)
    confirmar_contraseña = forms.CharField(max_length=50, widget=forms.PasswordInput)

    class Meta:
        model = Persona
        fields = '__all__'
        exclude=['es_empleado_publico', 'es_cliente','clave']

    def clean(self):
        cleaned_data = super().clean()
        contraseña = cleaned_data.get('contraseña')
        confirmar_contraseña = cleaned_data.get('confirmar_contraseña')

        if contraseña and confirmar_contraseña and contraseña != confirmar_contraseña:
            raise ValidationError('Las contraseñas no coinciden.')

        # Opcional: Puedes cifrar la contraseña antes de guardarla en la base de datos
        cleaned_data['clave'] = make_password(contraseña)
        
        return cleaned_data

source/apps/clientes/views.py
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import smtplib
from .models import *
from .forms import *
import random
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.hashers import make_password
from django.views.generic.edit import CreateView
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.crypto import get_random_string
from django.core.mail import send_mail

from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from ..clientes.models import Cliente
from ..empleadospublicos.models import EmpleadoPublico







        
        
            

source/apps/clientes/templates/cliente_alta.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h2>Formulario para el cliente</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" id="submitBtn">Guardar</button>
  </form>

  <!-- Muestra el mensaje de éxito y el enlace simulado de redirección -->
  {% if messages %}
    <div class="alert alert-success" role="alert">
      {{ messages|first }}
      <a href="#" onclick="simularRedireccion()">Haz clic aquí para simular la redirección</a>
    </div>
  {% endif %}

  <!-- Script para simular la redirección con un delay de 2 segundos -->
  <script>
    function simularRedireccion() {
      setTimeout(function () {
        // Simula la redirección a otra página o muestra un mensaje adicional
        alert('Se ha simulado la redirección. Ingrese el número de validación.')
        // Puedes redirigir a otra página con window.location.href si es necesario
      }, 2000)
    }
  </script>
{% endblock %}

source/apps/clientes/templates/confirmacion_cliente.html
{% extends 'base.html' %}

{% block content %}
  <h2>Correo enviado exitosamente</h2>
  <p>Se ha enviado un correo de confirmación a la dirección proporcionada. Por favor, revise su bandeja de entrada.</p>
{% endblock %}

source/apps/clientes/templates/dashboardCliente.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
  <link href="{% static 'Libs/css/dashboard.css' %}" rel="stylesheet" />
  {% block extra_css_nivel %}

  {% endblock %}
{% endblock %}

{% block content %}
  {% include 'navbarCliente.html' %}
  {% comment %} {% include 'navbarEmpleadoPublico.html' %}
  {% include 'navbarAdministrador.html' %} {% endcomment %}
  <div style="display: flex; justify-content: center; align-items: center; min-height: calc(100vh - 60px);">
    {% block contenedor %}
      <div class="cuadrado-background animate__animated animate__fadeIn">
        <h1 class="text-center titulo">¡Bienvenido {{ user }}!</h1>

        <div class="row">
          <div class="col-md-4 col-sm-12">
            <h5>Mutual asociada:</h5>
          </div>

          <div class="col-md-8 col-sm-12">
            <h5 class="negrita">{{ rol.cliente.mutual }}</h5>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4 col-sm-12">
            <h5>Ultima conexión:</h5>
          </div>
          <div class="col-md-8 col-sm-12">
            <h5>{{ ultimaConexion }}</h5>
          </div>
        </div>
      </div>
    {% endblock %}
  </div>
     
{% endblock %}

source/apps/clientes/templates/navbarAdministrador.html
{% extends 'navbarEmpleadoPublico.html' %}


{% block opcion_mutual_adicional %}
<li><hr class="dropdown-divider"></li>
<li>
  <a class="dropdown-item" href="{% url 'mutual:detalles_mimutual' %}">Crear</a>
</li>
<li>
  <a class="dropdown-item" href="{% url 'mutual:detalles_mimutual' %}">Buscar</a>
</li>

{% endblock %}

{% block dropdown_adicional %}
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Usuarios</a>
  <ul class="dropdown-menu">
    <li>
      <a class="dropdown-item" href="{% url 'mutual:detalles_mimutual' %}">Buscar</a>
    </li>
    <li>
      <a class="dropdown-item" href="{% url 'mutual:detalles_mimutual' %}">Crear Nuevo Usuario</a>
    </li>
    <li>
      <a class="dropdown-item" href="{% url 'mutual:detalles_mimutual' %}">Listado de Usuarios</a>
    </li>
  </ul>
</li>
{% endblock %}

source/apps/clientes/templates/navbarCliente.html
{% extends 'nav_bar.html' %}


{% block opcion_mutual %}
<li>
  <a class="dropdown-item" href="{% url 'mutual:detalles_mimutual' %}">Mi Mutual</a>
</li>
{% endblock %}

{% block opcion_declaracion_jurada %}
<li>
  <a class="dropdown-item" href="{% url 'mutual:declaracion_jurada' accion='declaracion' %}">Crear Nueva Declaración</a>
</li>
<li>
  <a class="dropdown-item" href="{% url 'mutual:historico' %}">Histórico</a>
  </li>
{% endblock %}
{% block opcion_ayuda %}
<li>
  <a class="dropdown-item" href="{% url 'pdf_manual_mutual' %}" target="_blank">Manual</a>
</li>
{% endblock %}

source/apps/clientes/templates/navbarEmpleadoPublico.html
{% extends 'nav_bar.html' %}


{% block opcion_mutual %}
<li>
  <a class="dropdown-item" href="{% url 'mutual:listado_mutual' %}">Listado de Mutuales</a>
</li>
{% block opcion_mutual_adicional %}
{% endblock %}

{% endblock %}

{% block opcion_declaracion_jurada %}
<li>
  <a class="dropdown-item" href="{% url 'mutual:declaracion_jurada' %}">Nuevo Periodo Declarativo</a>
</li>
<li>
  <a class="dropdown-item" href="{% url 'mutual:historico' %}">Periodo Declarado Vigente</a>
  </li>
  <li>
    <a class="dropdown-item" href="{% url 'mutual:declaracion_jurada_declarado' %}">Historial Periodos Declarados</a>
  </li>
  {% block opcion_declaracion_jurada_adicional %}
  {% endblock %}
{% endblock %}