source/apps/mutual/urls.py
# Importaciones del sistema
from django.urls import path
from .views import *
app_name = "mutual"

urlpatterns = [
    
    path('crearMutual/',MutualCreateView.as_view(), name="mutual_crear"),
    path('mutuales/listado', MutualesListView.as_view(), name="listado_mutual"),
    path('mutuales/editar/<int:pk>', EditarMutal, name="editar_mutual"),

    path('declaracionjurada/crear/<str:accion>/', DeclaracionJuradaCreateView.as_view(), name="declaracion_jurada"),
    path('declaracionjurada/historialDeclarado',DeclaracionJuradaDeclaradoListView.as_view(), name="declaracion_jurada_declarado_listado"),
    
    path('declaracionjurada/leer',leerDeclaracionJurada , name="leer_declaracion_jurada"),
    path('verificar_todas_leidas/<int:periodo_pk>/', verificar_todas_leidas, name='verificar_declaraciones_todas_leidas'),

    path('declaracionjurada/historico',HistoricoView.as_view(), name="historico"),
    path('DeclaracionJurada/<int:pk>/', descargarDeclaracion, name="descargarDeclaracion"),
    path('DeclaracionJurada/archivo/<int:pk>/', descargarArchivo, name="descargarArchivo"),


    path('periodos/periodo/crear', PeriodoCreateView.as_view(), name="periodo_crear"),
    path('periodos/periodo/vigente', periodoVigenteDetalle , name="periodo_vigente_detalle"),
    path('periodos/periodo/vigente/<int:pk>/mutuales/nopresentaron', periodoVigenteMutualNoPresento , name="mutual_no_presento"),
    path('periodos/periodo/vigente/<int:pk>/finalizar', finalizarPeriodo , name="finalizar_periodo"),
    path('periodos/periodo/vigente/<int:pk>/finalizar_crear_nuevo', finalizarPeriodoCrearNuevo , name="finalizar_periodo_crear_nuevo"),
    
    path('periodos/periodo/<int:pk>/comprimir', comprimirPeriodo, name="comprimir_periodo"),
    
    path('periodos/periodo/descargar', seleccionarPeriodoComprimir, name="comprimir_archivos_periodo"),
    
    
    path('exito/', mutual_exito, name='mutual_exito'),
    path('prueba/', tu_vista, name='t_vista'),
    path('datos/', DetalleMutualView.as_view(), name='detalles_mimutual'),
    path('confirmacion/', ConfirmacionView.as_view(), name='confirmacion'),
    path('visualizar_errores/', VisualizarErroresView.as_view(), name='visualizarE'),
    path('msj_informativo/', MsjInformativo.as_view(), name='msj_info'),

]

source/mutualWeb/urls.py
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from mutualWeb.views import *
from .views import *
from mutualWeb import views



urlpatterns = [
    #PRIINCIPALES
    # path('', bienvenida , name='index'),
    path('', RedirectView.as_view(url='login/', permanent=False), name='index'),
    path('admin_manager_ministerio/', admin.site.urls),
    path('dashboard/', dashboard, name='dashboard'),

    #APLICACIONES
    path('dashboard/clientes/', include('apps.clientes.urls')),
    path('dashboard/mutual/', include('apps.mutual.urls')),
    path('dashboard/personas/', include('apps.personas.urls')),
    path('', include('apps.users.urls')),
    path('home/app_reportes/',include('apps.reportes.urls')),

    path("selectable/", include("selectable.urls")),
    path('buscar_mutuales/', views.buscar_mutuales, name='buscar_mutuales'),
    
    # para abir los manuales
    path('manual_usuario_mutual/', abrirManualMutual, name="pdf_manual_mutual"),
    path('manual_usuario_operativos/', abrirManualOperativos, name="pdf_manual_operativos"),
    path('manual_usuario_administrador/', abrirManualAdministrador, name="pdf_manual_administrador"),
]

handler404 = "mutualWeb.views.pagina_no_encontrada"

source/apps/mutual/views.py
from io import BytesIO
import io
import subprocess
from reportlab.pdfgen import canvas
from django.shortcuts import get_object_or_404
from django.http import FileResponse, Http404
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
import os
from typing import Any
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import CreateView , TemplateView , DetailView , UpdateView

from apps.mutual.lookups import PeriodoLookup
from .models import DeclaracionJuradaDetalles, DetalleMutual, Mutual , DeclaracionJurada, Periodo
from .forms import *
from django.urls import reverse_lazy
from django.contrib import messages
from django.db import transaction
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from ..users.models import UserRol
import re
import locale
from datetime import datetime
from timezonefinder import TimezoneFinder
from django.utils.translation import gettext as _
from datetime import date
from django.views.generic import ListView
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import permission_required, login_required
from django.http import JsonResponse
from django.db.models import Q
from dateutil.relativedelta import relativedelta
import datetime
from datetime import datetime
from django.http import HttpResponse
from openpyxl import Workbook



from django.http import HttpResponse




def tu_vista(request):
    data = Mutual.objects.all()
    return render(request, 'tu_vista.html', {'data': data})

def obtener_mes_y_anio_actual():
        # Encontrar la zona horaria basada en la ubicación
        tz_finder = TimezoneFinder()
        ubicacion = tz_finder.timezone_at(lng=-64.1428, lat=-31.4201)  # Coordenadas de Buenos Aires
        fecha_hora_actual = datetime.today()

        # Obtener el mes y el año actual de forma dinámica en español
        mes_actual = fecha_hora_actual.month
        año_actual = fecha_hora_actual.year
        
        periodo = datetime(año_actual, mes_actual, 1).date()
       
        return periodo

def es_numerico(cadena):
        """Verifica si una cadena está compuesta solo por dígitos."""
        return bool(re.match("^\d+$", cadena))

def validar_numero(self, line_content, line_number, inicio, fin, tipo_numero, listErrores, inserto_error):
        """Valida un número en una línea."""
        numero = line_content[inicio:fin]
        mensaje = f"{tipo_numero}: {numero}"

        if not es_numerico(numero):
            inserto_error = True
            listErrores.append(f"Error: La línea {line_number}. {mensaje} tiene caracteres no numéricos. Línea: {line_content}")

def desglozarLinea(line_content):
    documento = line_content[3:16]
    concepto = line_content[16:20]
    importe = line_content[20:31]
    fecha_str_inicio = line_content[31:39]
    fecha_str_fin = line_content[39:47]
    cupon = line_content[47:54]
    return documento, concepto, importe, fecha_str_inicio, fecha_str_fin, cupon

def validarDocumento(self, documento, error, inserto_error):
    if not es_numerico(documento):
        inserto_error[0] = True
        error['error_detalle_documento'] = 'El Documento no es numerico'
        error['error_documento'] = True

def validarImporte(self, importe, error, inserto_error):
    if not es_numerico(importe):
        inserto_error[0] = True
        error['error_detalle_importe'] = 'El Importe no es numerico'
        error['error_importe'] = True

def validarConcepto(self, concepto, error, inserto_error, tipo_archivo):
    if not es_numerico(concepto):
        error['error_concepto'] = True

        error['error_detalle_concepto'] = 'El concepto no es numerico'
        inserto_error[0] = True
    else:
        concepto = int(concepto)
        if not existeConcepto(self, concepto, tipo_archivo):
            print("NO EXISTE EL CONCEPTO VINCULADO A LA MUTUAL")
            inserto_error[0] = True
            error['error_concepto'] = True
            error['error_detalle_concepto'] = 'El concepto no esta vinculado a su Mutual'

def validarCupon(self, cupon, error, inserto_error):
    if not es_numerico(cupon):
        inserto_error[0] = True
        error['error_detalle_cupon'] = 'El cupón no es numerico'
        error['error_cupon'] = True

def validarCuota(self, cuota, error, inserto_error):
    if not es_numerico(cuota):
        inserto_error[0] = True
        error['error_detalle_cuota'] = 'La cuota no es numerico'
        error['error_cuota'] = True

def longitudValida(line_content, LONGITUD_P):
    return len(line_content) == LONGITUD_P

#------------------------ VALIDACIÓN PARA EL CONCEPTO ------------------------
def validar_concepto(self, line_content, line_number, inicio, fin, tipo_numero, tipo_archivo, listErrores):

    validar_numero(self, line_content, line_number, inicio, fin, tipo_numero, listErrores)
    concepto = int(line_content[inicio:fin])

    if not existeConcepto(self, concepto, tipo_archivo):
        numero = line_content[inicio:fin]
        mensaje = f"{tipo_numero}: {numero}"
        listErrores.append(f"Error: La línea {line_number}. {mensaje} no esta vinculado a su mutual. Linea: {line_content})")
     

#------------------------ OINTENGO EL TOTAL DEL IMPORTE ------------------------
def obtenerImporte(self, importe):
    importe_str = importe.lstrip('0')  # Remove leading zeros
    if not importe_str:
        importe_str = '0'
    importe_formatted = float(importe_str) /100 
    return importe_formatted

#--------------- VALIDA LA EXISTENCIA DEL CONCEPTO ------------------------
def existeConcepto(self, concepto, tipo_archivo):
    mutual = obtenerMutualVinculada(self)
    if mutual and mutual.detalle.exists():
        detalle_mutual = mutual.detalle.filter(tipo=tipo_archivo).first()
        if concepto == detalle_mutual.concepto_1 or concepto == detalle_mutual.concepto_2:
            return True
    return False

def obtenerMutualVinculada(self):
    userRol = UserRol.objects.get(user=self.request.user)
    mutual = userRol.rol.cliente.mutual
    return mutual

def obtenerPeriodoVigente(self):
  try:
        periodo = Periodo.objects.get(fecha_fin = None)
        return periodo
        
  except Periodo.DoesNotExist: 
         return None


def fecha_es_mayor_por_meses(fecha2):
    MESES = 2
    fecha1 = datetime.now()

    # Convierte fecha2 a un objeto datetime para la comparación
    fecha2_datetime = datetime.combine(fecha2, datetime.min.time())
    
    nueva_fecha = fecha2_datetime + relativedelta(months=MESES)
    
    # Compara la nueva fecha con la fecha1
    return nueva_fecha < fecha1
#-----------------CONFIRMACION DJ---------------------------
class ConfirmacionView(TemplateView):
    template_name = 'confirmacion.html'
    success_url = '/confirmacion/'
    
    
    def get(self, request, *args, **kwargs):
        if request.GET.dict():
            super.get(self)
        else:
         return redirect('dashboard')
       
        
    
#-----------------CONFIRMACION DJ---------------------------
class MsjInformativo(TemplateView):
    template_name = 'msj_informativo.html'
    success_url = '/msj_info/'
    
    
    def get(self, request, *args, **kwargs):
        if request.GET.dict():
            super.get(self)
        else:
         return redirect('dashboard')
       
        


def existeBorrador(self):
            try: 
                    mutual = obtenerMutualVinculada(self) 
                    dj = DeclaracionJurada.objects.get(mutual = mutual , es_borrador = True)
                    return True

            except DeclaracionJurada.DoesNotExist:
                return False
    
            
# ---------------------------------------------------------

class VisualizarErroresView(TemplateView):
    template_name = 'visualizar_errores.html'
    success_url = '/visualizarE/'
    
    def get(self, request, *args, **kwargs):
        if request.GET.dict():
            super.get(self)
        else:
         return redirect('dashboard')

#--------------- DECLARACIÓN JURADA ------------------------
class DeclaracionJuradaCreateView(LoginRequiredMixin,PermissionRequiredMixin, CreateView):
    login_url = '/login/'
    permission_required = "clientes.permission_cliente_mutual"
    model = DetalleDeclaracionJurada
    form_class = FormularioDJ
    template_name = "dj_alta.html"
    success_url = reverse_lazy('mutual:declaracion_jurada', args=['accion=declarar'])

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        if 'confirmacion' in request.POST:
            return self.confirmar_declaracion(request)
        elif 'cancelar' in request.POST:
            return self.cancelar_declaracion(request)
        elif 'cargarDeclaracion' in request.POST:
            return self.cargar_declaracion(request)
        else:
            return super().post(request, *args, **kwargs)
        
    def confirmar_declaracion(self, request: HttpRequest) -> HttpResponse:
        mutual = obtenerMutualVinculada(self)
        nroRectificativa = 0
        if existeBorrador(self):
            nroRectificativa = self.obtener_numero_rectificativa(mutual)
            print(nroRectificativa)
            self.eliminar_declaracion_jurada(mutual)
            self.actualizar_declaracion_jurada(mutual, nroRectificativa)
            messages.success(self.request, "Declaracion Jurada confirmada")
            return redirect('mutual:historico')
        else:
            return redirect('dashboard')

    def obtener_numero_rectificativa(self, mutual):
        try:
            periodo = obtenerPeriodoVigente(self)
            dj = DeclaracionJurada.objects.get(mutual=mutual, es_borrador=False, periodo=periodo)
            return dj.rectificativa + 1
        except DeclaracionJurada.DoesNotExist:
            return 0

    def eliminar_declaracion_jurada(self, mutual):

source/apps/mutual/templates/cabecera_table_columna_archivo.html
<th>LINEA</th>
<th>DOCUMENTO</th>
<th>CONCEPTO</th>
<th>IMPORTE</th>
<th>FECHA INICIO</th>
<th>FECHA FIN</th>
<th>CUPÓN</th>

source/apps/mutual/templates/cuerpo_table_columna_archivo.html
<td class="negrita">{{error.fila}}</td>
{% if error.error_documento %}
  <td class="table-danger">{{error.documento}}</td>
{% else %}
  <td class="table-success">{{error.documento}}</td>
{% endif %}

{% if error.error_concepto %}
  <td class="table-danger">{{error.concepto}}</td>
{% else %}
  <td class="table-success">{{error.concepto}}</td>
{% endif %}

{% if error.error_importe %}
<td class="table-danger">{{error.importe}}</td>
{% else %}
<td class="table-success">{{error.importe}}</td>
{% endif %}

{% if error.error_fechaInicio and error.error_fechaFin %}
  <td class="table-danger">{{error.fechaInicio}}</td>
  <td class="table-warning">{{error.fechaFin}}</td>
{% else %}
  {% if error.error_fechaInicio %}
    <td class="table-danger">{{error.fechaInicio}}</td>
  {% else %}
    <td class="table-success">{{error.fechaInicio}}</td>
  {% endif %}

  {% if error.error_fechaFin %}
    <td class="table-danger">{{error.fechaFin}}</td>
  {% else %}
    <td class="table-success">{{error.fechaFin}}</td>
    {% endif %}
{% endif %}

{% if error.error_cupon %}
<td class="table-danger">{{error.cupon}}</td>
{% else %}
<td class="table-success">{{error.cupon}}</td>
{% endif %}


          

source/apps/mutual/templates/dj_declarados_list.html
{% extends 'dashboardEmpleadoPublico.html' %}
{% load static %}

{% block extra_css_nivel %}
  <link href="{% static 'Libs/css/historico.css' %}" rel="stylesheet" />
       <style>
  .tipoFecha {
    display: block;
    float: left;
    width: 50%;
  }
  </style>
{% endblock %}

{% block contenedor %}
<div class=" container cuadrado-background animate__animated animate__fadeIn">
  <h3 class="text-center titulo">{{ titulo }}</h3>
  <hr>

  <form method="get" class="mb-7">
    {% csrf_token %}
    <div class="container">
      <div class="row">

        <div class="col">
          {{filter_form.alias}}
        </div>
        <div class="col">
          {{filter_form.periodo}}
        </div>
        <div class="col">
          <button type="submit" class="btn btn-sm btn-primary btn-circle">
            <i class="fa-solid fa-filter"></i>
          </button>
        </div>
      </div>
    </div>
  </form>

  <hr>

  <form method="post" action="{% url 'mutual:leer_declaracion_jurada' %}" class="mb-3" id="miFormulario">
  {% csrf_token %}
    <div class=" table-responsive">
      <table class="table table-sm  table-striped table-hover ">
        <thead>
          <tr>
            <th>#</th>
            <th>Período</th>
            <th>Mutual</th>
            <th>Cuit</th>
            <th>Fecha lectura</th>
            <th class="text-center">Rectificativa</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for declaracion in page_obj %}
          <tr>
            <td class="negrita"> {{ page_obj.start_index|add:forloop.counter0 }}</td>
            <td> {{ declaracion.periodo.mes_anio|date:'Y/m' }}</td>
            <td> {{ declaracion.mutual.alias }}</td>
            <td> {{ declaracion.mutual.cuit }}</td>
            <td> {{ declaracion.fecha_lectura|date:'Y/m/d' }}</td>
            <td class="text-center"> {{ declaracion.rectificativa }}</td>

            <td class="text-end">
              <button type="button" class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#modalDetalle_{{declaracion.pk}}">
                <i class="fa-regular fa-eye"></i> ver
              </button>
              {% include "detalle_declaracion_jurada.html" %}
              <a class="btn" href="{% url 'mutual:descargarDeclaracion' declaracion.pk %}">
                <i class="fa-solid fa-download"></i>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </form>

  {% include "pagination_listado.html" %}

</div>

<link href="{% static 'selectable/css/dj.selectable.css' %}" type="text/css" media="all" rel="stylesheet">
<script type="text/javascript" src="{% static 'Libs/js/jquery-1.11.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'Libs/js/jquery-iu.js' %}"></script>
<script type="text/javascript" src="{% static 'selectable/js/jquery.dj.selectable.js' %}"></script>

{% endblock %}

source/apps/mutual/templates/dj_list.html
{% extends 'dashboardCliente.html' %}
{% load static %}

{% block extra_css_nivel %}
  <link href="{% static 'Libs/css/historico.css' %}" rel="stylesheet"/>
{% endblock %}

{% block contenedor %}
  <div class="container cuadrado-background animate__animated animate__fadeIn">
    <h3 class="text-center titulo">{{ titulo }}</h3>
    
    <form method="get" class="mb-7">
      {% csrf_token %}
      
      {{filter_form.periodo}}
      <button class="btn btn-success btn-block btn-sm" type="submit" ><i class="fa-solid fa-magnifying-glass"></i></button>

    </form>
    <div class="table-responsive ">
      <table class="table">
        <thead>
        <tr>
          <th>#</th>
          <th>Periodo</th>
          <th class="text-center">Leido</th>
          <th class="text-center">Rectificatica</th>
          <th>Fecha de subida</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for declaracion in page_obj %}
          <tr>
            <td class="negrita"> {{ page_obj.start_index|add:forloop.counter0 }}</td>
            <td>{{ declaracion.periodo.mes_anio|date:'Y/m' }}</td>
            <td class="text-center">
              {% if declaracion.es_leida %}
              <i class="fa-regular fa-circle-check" style="color: #004200;" ></i>
              {% else %}
              <i class="fa-solid fa-circle-exclamation" style="color: #ffa500;"></i>
              {% endif %}
            </td>
            <td class="text-center"> {{ declaracion.rectificativa }}</td>
            <td>{{ declaracion.fecha_subida|date:"Y/m/d H:i:s" }}</td>
            
            <td class="text-end">
              <button type="button" class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#modalDetalle_{{declaracion.pk}}">
                <i class="fa-regular fa-eye"></i> ver
              </button>
              
              {% if not declaracion.es_leida %}
              <a class="btn btn-warning btn-sm" href="{% url 'mutual:declaracion_jurada' accion='rectificar' %}">
                <i class="fa-solid fa-rotate-right"></i>
                Rectificar</a>
              {% endif %}
              <a class="btn" href="{% url 'mutual:descargarDeclaracion' declaracion.pk %}" title="Acuse de recibo DJ">
                <i class="fa-solid fa-download"></i>
              </a>
            </td>
          </tr>
          {% include "detalle_declaracion_jurada.html" %}
        {% endfor %}
      </tbody>
    </table>
    </div>

    <nav aria-label="...">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link small-btn" href="?page=1">&laquo; Primero</a>
          </li>
          <li class="page-item">
            <a class="page-link small-btn" href="?page={{ page_obj.previous_page_number }}">Anterior</a>
          </li>
        {% endif %}
    
          
        {% for num in page_obj.paginator.page_range %}
          <li class="page-item {% if num == page_obj.number %}active{% endif %}">
            <a class="page-link small-btn" href="?page={{ num }}">{{ num }}</a>
          </li>
        {% endfor %}
    
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link small-btn" href="?page={{ page_obj.next_page_number }}">Siguiente</a>
          </li>
          <li class="page-item">
            <a class="page-link small-btn" href="?page={{ page_obj.paginator.num_pages }}">Último &raquo;</a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </div>

<link href="{% static 'selectable/css/dj.selectable.css' %}" type="text/css" media="all" rel="stylesheet">
<script type="text/javascript" src="{% static 'Libs/js/jquery-1.11.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'Libs/js/jquery-iu.js' %}"></script>
<script type="text/javascript" src="{% static 'selectable/js/jquery.dj.selectable.js' %}"></script>

{% endblock %}

source/apps/mutual/templates/modal_confirmar_fin_periodo.html
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Finalizar Periodo</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          ¿Deseas finalizar el periodo? Para finalizar el periodo tienen que estar <strong>todas las declaraciones juradas leidas.</strong>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
          
          <a href="{% url 'mutual:finalizar_periodo' pk=periodo.pk %}" class="btn btn-outline-success"> Finalizar </a>
          <a href="{% url 'mutual:finalizar_periodo_crear_nuevo' pk=periodo.pk %}" class="btn btn-outline-success"> Finalizar y crear uno nuevo </a>
        </div>
      </div>
    </div>
  </div>

source/apps/mutual/templates/modal_detalle_declaracion_jurada.html
<div class="modal fade" id="modalDetalle_{{mutual.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-sm" >
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">{{mutual.nombre}}</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            {% for detalle in mutual.detalle.all %}
            <h5 class="detalle-tipo">
                {% if detalle.tipo == 'P' %}Préstamo
                {% else %}Reclamo
                {% endif %}
            </h5>
            <ul>
                <li>
                    Origen: {{ detalle.origen }}.txt
                </li>
                <li>
                    Destino: {{ detalle.destino }}.txt
                </li>
                <li>
                    Concepto: {{ detalle.concepto_1 }} 
                    {% if detalle.concepto_2 != 0 %}
                    y  {{ detalle.concepto_2 }}
                    {% endif %}
                </li>
            </ul>
            <hr />
          {% endfor %}

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  

source/apps/mutual/templates/mostrar_detalle_error.html
</br>
<h5>Listado de Errores por Linea </h5>
{% for error in erroresPrestamo %}
<li>
    Linea <strong>{{ error.fila }}</strong>: {{ error.detalle }}
</li>
{% endfor %}

source/apps/mutual/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'dashboard' %}">
        <img src = "{% static 'images/escudo.ico' %}" alt="Logo" width="23" height="25" class="d-inline-block align-text-top">
        DGC
      </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Mutual</a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'mutual:mutual_crear' %}">Crear Mutual</a>
            </li>
          </ul>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Declaración Jurada</a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="#">Crear Declaración Jurada</a>
              
            </li>
            
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Usuarios</a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'users:register' %}">Crear Usuario Mutual</a>
              <a class="dropdown-item" href="{% url 'users:register' %}">Crear Usuario Empleado Público</a>
              <a class="dropdown-item" href="{% url 'users:register' %}">Crear Usuario Administrador</a>
            </li>
          </ul>
        </li>

      </ul>

      <div class="btn-group">
        <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
          <span class="bi bi-person"></span> Hola, {{user}}
        </button>
        <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg-start">
          <li><a class="dropdown-item" href="#">Ver perfil</a></li>
          <li><a class="dropdown-item" href="#">Editar perfil</a></li>
          <li><a class="dropdown-item" href="#">
            <i class="fa-solid fa-lock"></i>
            Cerrar Ssssesión</a></li>
        </ul>
      </div>

    </div>
  </div>
</nav>