source/apps/users/urls.py
from django.shortcuts import render
from .views import *
from django.urls import path

app_name = "users"

urlpatterns = [
  path('login/', CustomLoginView.as_view(), name='login'),
  path('cerrar_session/',cerrar_session,name='cerrar_session'),
  path('usuarios/cambiar_estado/<int:pk>',cambiarEstado,name='cambiar_estado'),
  path('usuarios/listado', UserListView.as_view(), name='usuarios_listado'),
  path('usuarios/menu/', Menu.as_view(), name='menu_user'), 
  path('usuarios/usuario/mutual/crear', RegisterUserMutalView.as_view(), name='register_U_M'), 
  path('usuarios/usuario/emplpublico/crear', RegistereEmpleadoPublicoView.as_view(), name='register_E_P'),
  path('usuarios/usuario/administrador/crear', RegistereAdministradorView.as_view(), name='register_A'),
  path('cambiar-password/', CustomPasswordChangeView.as_view(), name='cambiar_password'),
  path('usuarios/cambiar-password-admin/<int:pk>', PasswordChangeAdmnistrador, name='cambiar_password_admin'),
  
  # path('exitoM/', register_user_mutual_exito, name='register_userM_exito'),
]

source/mutualWeb/urls.py
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from mutualWeb.views import *
from .views import *
from mutualWeb import views



urlpatterns = [
    #PRIINCIPALES
    # path('', bienvenida , name='index'),
    path('', RedirectView.as_view(url='login/', permanent=False), name='index'),
    path('admin_manager_ministerio/', admin.site.urls),
    path('dashboard/', dashboard, name='dashboard'),

    #APLICACIONES
    path('dashboard/clientes/', include('apps.clientes.urls')),
    path('dashboard/mutual/', include('apps.mutual.urls')),
    path('dashboard/personas/', include('apps.personas.urls')),
    path('', include('apps.users.urls')),
    path('home/app_reportes/',include('apps.reportes.urls')),

    path("selectable/", include("selectable.urls")),
    path('buscar_mutuales/', views.buscar_mutuales, name='buscar_mutuales'),
    
    # para abir los manuales
    path('manual_usuario_mutual/', abrirManualMutual, name="pdf_manual_mutual"),
    path('manual_usuario_operativos/', abrirManualOperativos, name="pdf_manual_operativos"),
    path('manual_usuario_administrador/', abrirManualAdministrador, name="pdf_manual_administrador"),
]

handler404 = "mutualWeb.views.pagina_no_encontrada"

source/apps/users/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

from apps.users.lookups import UsernameLookup
from mutualWeb.utils.mensajes import mensaje_advertencia
from ..mutual.models import Mutual

class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Personaliza los campos si es necesario
        self.fields['old_password'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Contraseña actual'})
        self.fields['new_password1'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Nueva contraseña'})
        self.fields['new_password2'].widget = forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirmar nueva contraseña'})


class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(label='Usuario', widget=forms.TextInput(attrs={'autofocus': True}))
    password = forms.CharField(label='Contraseña', widget=forms.PasswordInput)


class RegisterUserMutualForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text="Debe incluir un signo @ en la dirección de correo electrónico.")
    mutual = forms.ModelChoiceField(
        queryset=Mutual.objects.all(),
        required=True,
        help_text="Seleccione la mutual que gestionará",
        widget=forms.Select(attrs={'class': 'form-select'})
    ) 
    
    class Meta:
        model = User  
        fields = UserCreationForm.Meta.fields + ('email',)
    
    
    def clean_username(self):
        
        username = self.cleaned_data.get('username')
        if User.objects.filter(username = username).exists():
            raise forms.ValidationError("Este nombre de usuario ya esta en uso. Por favor, elige otro.")
        return username    

    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        # Validar que el correo electrónico sea único
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Este correo electrónico ya está en uso. Por favor, elige otro.")
        
        # Validar que el correo electrónico incluya un signo @
        if '@' not in email:
            raise forms.ValidationError("El correo electrónico debe incluir un signo @.")
        
        return email



class RegisterUserEmpleadoPublicoForm(UserCreationForm):
    email = forms.EmailField(required=True, help_text="Debe incluir un signo @ en la dirección de correo electrónico.")
    
    class Meta:
        model = User  
        fields = UserCreationForm.Meta.fields + ('email',)
        
    def clean_email(self):
        email = self.cleaned_data.get('email')
        # Validar que el correo electrónico sea único
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Este correo electrónico ya está en uso. Por favor, elige otro.")
        
        # Validar que el correo electrónico incluya un signo @
        if '@' not in email:
            raise forms.ValidationError("El correo electrónico debe incluir un signo @.")
        
        return email


from selectable.forms import AutoCompleteSelectField, AutoComboboxSelectWidget

class UserFilterForm(forms.Form):
    username = AutoCompleteSelectField(
        lookup_class=UsernameLookup,
        required=False,
        widget=AutoComboboxSelectWidget(UsernameLookup, attrs={'class': 'form-control', 'placeholder': 'Alias'})
    )
    # email = forms.EmailField(label='Correo electrónico', required=False, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'}))
    is_active_choices = (
        ('1', 'Activo'),
        ('0', 'Inactivo'),
    )
    is_active = forms.MultipleChoiceField(label='Estado', choices=is_active_choices, required=False, widget=forms.CheckboxSelectMultiple)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Nombre de usuario'
        self.fields['is_active'].widget.attrs['class'] = 'form-check-input'
        self.fields['is_active'].widget.attrs['style'] = 'display: inline-block;'  # Para mostrar en dos columnas
        self.fields['is_active'].widget.attrs['class'] = 'list-unstyled'  # Eliminar viñetas de la lista

source/apps/users/views.py
from datetime import timezone
from pyexpat.errors import messages
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.views import View
from mutualWeb import forms
from mutualWeb.utils.mensajes import mensaje_error, mensaje_exito
from ..administradores.models import Administrador
from .forms import CustomLoginForm, CustomPasswordChangeForm, RegisterUserMutualForm, RegisterUserEmpleadoPublicoForm, UserFilterForm
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView
from .views import LoginView
from ..clientes.models import Cliente
from ..personas.models import Persona
from ..mutual.models import Mutual
from ..empleadospublicos.models import EmpleadoPublico
from .models import UserRol
from django.contrib.auth.models import User,Permission
from django.db import transaction
from django.contrib.auth import logout
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from django.views.generic import ListView
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import FormView
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.views.generic import View
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import permission_required, login_required


def obtenerPermiso(name):
    # Precondicion: {name} Exits in {"administador","cliente","empleadoPublico"}
    if name == "administrador":
        content_type = ContentType.objects.get_for_model(Administrador)
        permiso, creado = Permission.objects.get_or_create(
            codename='permission_administrador',
            name='Control total administrador',
            content_type=content_type,
        )
        return permiso
    
    if name == "cliente":
        content_type = ContentType.objects.get_for_model(Cliente)
        permiso, creado = Permission.objects.get_or_create(
            codename='permission_cliente_mutual',
            name='Control total cliente Mutual',
            content_type=content_type,
        )
        return permiso
    
    if name == "empleadoPublico":
        content_type = ContentType.objects.get_for_model(EmpleadoPublico)
        permiso, creado = Permission.objects.get_or_create(
            codename='permission_empleado_publico',
            name='Control total empleado público',
            content_type=content_type,
        )
        return permiso

def cerrar_session(request):
    userRol = UserRol.objects.get(user = request.user )
    userRol.ultimaConexion = request.user.last_login
    userRol.save()
    logout(request)
    return redirect('users:login')

@login_required(login_url="/login/")
@permission_required('administradores.permission_administrador', raise_exception=True)
def cambiarEstado(request, pk):
    if request.method == 'POST':
        try:
            user = User.objects.get(pk = pk)
            estado = user.is_active
            user.is_active = not estado 
            user.save()
            messages.success(request, "Estado del usuario: "+ str(User.username) +" cambiado.")
        except User.DoesNotExist:
            print("no cambiado")
    return redirect('users:usuarios_listado')

def register_user_mutual_exito(request):
    return render(request,'registrar_usuario_mutual_exito.html')

class Menu(LoginRequiredMixin,PermissionRequiredMixin,TemplateView):
    template_name = 'menu.html'
    success_url = '/menu_user/'
    login_url = '/login/'
    permission_required = "administradores.permission_administrador"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Creación de usuarios'
        return context


class CustomLoginView(LoginView, View):
    template_name = 'login_acceso.html'
    form_class = CustomLoginForm
    success_url = reverse_lazy('mutualWeb:dashboard')
    
    def get(self, request, *args: str, **kwargs):
        if request.user.is_authenticated:
           return redirect('dashboard')
        return super().get(request, *args, **kwargs)
    
    def form_invalid(self, form):
        if not self.request.user.is_active :
           messages.error(self.request, 'Usuario Inactivo, loggeo no permitido')
           return redirect('users:login')
        return super().form_invalid(form)
    
    
class RegisterUserMutalView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name ='registrar_usuario_mutual.html'
    form_class = RegisterUserMutualForm
    success_url = reverse_lazy('users:register_U_M')
    login_url = '/login/'
    permission_required = "administradores.permission_administrador"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Registro de usuario para una Mutual'
        
        mutuales = Mutual.objects.all().filter(activo=True)
        context['mutuales'] = mutuales

        return context
    

          
    def form_valid(self,form):
        # Verifica si el correo electrónico no contiene el símbolo "@"

  
        correo = form.cleaned_data["email"]
        try:
            with transaction.atomic():
                p = Persona(
                    correo = correo,
                    es_cliente = True
                )

                p.save()

                nombre = form.cleaned_data["mutual"]
                e = Mutual.objects.get(alias = nombre)

                c = Cliente (
                    persona = p,
                    mutual = e,
                    tipo = Cliente.TIPO
                )
                c.register
                c.save()
                form.save() 
                
                user = User.objects.get(username=form.cleaned_data["username"])
                permiso = obtenerPermiso("cliente")
                user.user_permissions.add(permiso)
                UserRol.objects.create(user = user , rol = c)                
                mensaje_exito(self.request, f'Usuario creado para una mutual con exito.')                
                return super().form_valid(form)
        except Exception:   
            mensaje_error(self.request, f'No se pudo crear el usuario')
            return super().form_invalid(form)
            
            



class RegistereEmpleadoPublicoView(LoginRequiredMixin, PermissionRequiredMixin , CreateView):
    template_name ='registrar_usuario.html'
    form_class = RegisterUserEmpleadoPublicoForm
    success_url = reverse_lazy('users:usuarios_listado')
    login_url = '/login/'
    permission_required = "administradores.permission_administrador"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Registro de Usuario Empleado Público'
        return context
    
   
          
    def form_valid(self,form):

     
            correo = form.cleaned_data["email"]
            try:   
                with transaction.atomic(): 
                    p = Persona(
                        correo = correo,
                        es_empleado_publico = True
                    )
                    
                    p.save()
                    
                    e =  EmpleadoPublico(
                        persona = p,
                        tipo = EmpleadoPublico.TIPO
                    )
                    e.register
                    e.save()
                    form.save() 
                    user = User.objects.get(username=form.cleaned_data["username"])
                    permiso = obtenerPermiso("empleadoPublico")
                    user.user_permissions.add(permiso)
                    UserRol.objects.create(user = user , rol = e)
                    mensaje_exito(self.request, f'Usuario creado con exito.')                

                    return super().form_valid(form)
            except Exception:
               mensaje_error(self.request, f'No se pudo crear el usuario')
               return super().form_invalid(form)
                
   

class RegistereAdministradorView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
        template_name ='registrar_usuario.html'
        form_class = RegisterUserEmpleadoPublicoForm
        success_url = reverse_lazy('users:usuarios_listado')
        login_url = '/login/'
        permission_required = "administradores.permission_administrador"

        def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context['titulo'] = 'Registro Usuario Adminsitrador'
            return context
            
            
        def form_valid(self,form):
            # Verifica si el correo electrónico no contiene el símbolo "@"
            if 'email' in form.errors and 'El correo electrónico debe incluir un signo @.' in form.errors['email']:
                messages.error(self.request, 'El correo electrónico debe incluir un signo @.')
                return super().form_invalid(form)
            else:
                correo = form.cleaned_data["email"]
                try:   
                    with transaction.atomic():           
                        p = Persona(
                            correo = correo,
                            es_admin = True
                        )
                        
                        p.save()
                        e =  Administrador(
                            persona = p,
                            tipo = Administrador.TIPO
                        )
                        e.register
                        e.save()
                        form.save() 

source/apps/users/templates/cambiar_password.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
  <link href="{% static 'Libs/css/dashboard.css' %}" rel="stylesheet" />
  {% block extra_css_nivel %}

  {% endblock %}
{% endblock %}


{% block content %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'dashboard' %}">
        <img src="{% static 'images/escudo.ico' %}" alt="Logo" width="23" height="25" class="d-inline-block align-text-top" />
        DGC
      </a>    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
</nav>

<div style="display: flex; justify-content: center; align-items: center; min-height: calc(100vh - 60px);">
  <div class="container cuadrado-background animate__animated animate__fadeIn">
    <h4 class="text-center">Cambio de contraseña</h4>
  
    <form method="post" autocomplete="off">
      {% csrf_token %}
      {{form.as_p}}
      <br />
      <div class="text-center">
        
        <a  href="{% url 'dashboard' %}" class="btn btn-secondary"> 
          <i class="fa-solid fa-house fa"></i>
          Pagina principal
        </a>
        {% comment %} <a  href="{% url 'users:usuarios_listado' %}" class="btn btn-primary"> 
          <i class="fa-solid fa-list"></i>
          Volver al listado
        </a> {% endcomment %}
        <button type="submit" class="btn btn-success"><i class="fa-solid fa-check"></i> Cambiar contraseña</button>
      </div>
    </form>
  </div>
</div>

    <script>
  function togglePassword_one() {
    var passwordInput = document.querySelector(".password-input");
    var passwordIcon = document.getElementById("password-icon");
  
    if (passwordInput.type === "password") {
      passwordInput.type = "text";
      passwordIcon.className = "fa-solid fa-eye-slash";
    } else {
      passwordInput.type = "password";
      passwordIcon.className = "fa-solid fa-eye";
    }
  }

  function togglePassword_two() {
    var passwordInput = document.querySelector(".password-input-two");
    var passwordIcon = document.getElementById("password-icon_two");

    if (passwordInput.type === "password") {
      passwordInput.type = "text";
      passwordIcon.className = "fa-solid fa-eye-slash";
    } else {
      passwordInput.type = "password";
      passwordIcon.className = "fa-solid fa-eye";
    }
  }
</script>
{% endblock %}

source/apps/users/templates/listado_usuarios.html
{% extends 'dashboardAdministrador.html' %}
{% load static %}

{% block extra_css_nivel %}
  <link href="{% static 'Libs/css/historico.css' %}" rel="stylesheet" />
{% endblock %}


{% block contenedor %}
<div class=" container cuadrado-background">
  <h3 class="text-center titulo">{{ titulo }}</h3>
  <hr>

  <form method="get">
    {% csrf_token %}
    <div class="container">
      <div class="row">
        <div class="col">
            {{ filter_form.username }}
        </div>
        <div class="col">
          {{ filter_form.is_active }}
        </div>

        <div class="col">
          <button type="submit" class="btn btn-sm btn-primary btn-circle">
          <i class="fa-solid fa-filter"></i>
        </button>
      </div>
    </div>
    <hr>
  </form>


  <div class=" table-responsive">
    <table class="table table-sm  table-striped table-hover ">
      <thead>
        <tr>
          <th >#</th>
          <th>Username</th>
          <th>Email</th>
          <th>Ultima conexión</th>
          <th class="text-center">Estado</th>
          <th colspan="2"></th>
        </tr>
      </thead>
      <tbody>
        {% for user in object_list %}
        <tr>
            <td class="negrita">{{ forloop.counter }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.date_joined }}</td>
            
            <td class="text-center">
              {% if user.is_active %} 
                <i class="fa-solid fa-circle-check" style="color: #306b00;"></i> 
              {% else %}
                <i class="fa-solid fa-circle-xmark" style="color: #7a0000;"></i> 
              {% endif %}
              </td>
      
            <td>
                <a class="btn btn-sm btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#modalpass_{{user.pk}}">
                     <i class="fa-solid fa-lock"></i>
                    Cambiar contraseña
                  </a>
            </td>
            
            <td> 
                 {% if not user.is_active %}  
                 <a class="btn btn-sm " data-bs-toggle="modal" data-bs-target="#cambiarEstado_{{user.pk}}">
                      <i class="fa-regular fa-circle-up" style="color: #1dc93f;"></i>
                    Dar de Alta
                  </a>
                  {% else %}
                  <a class="btn btn-sm " data-bs-toggle="modal" data-bs-target="#cambiarEstado_{{user.pk}}">
                      <i class="fa-regular fa-circle-down" style="color: #ea1a1a;"></i>
                    Dar de Baja
                  </a>
                {% endif %}
            </td>




        </tr>
        {% include "modal_cambiar_contrasenia.html" %}
        {% include "modal_cambiar_estado_user.html" %}
        {% endfor %}
        

      </tbody>
    </table>
    {% include "pagination_listado.html" %}
  </div>
  <link href="{% static 'selectable/css/dj.selectable.css' %}" type="text/css" media="all" rel="stylesheet">
  <script type="text/javascript" src="{% static 'Libs/js/jquery-1.11.2.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'Libs/js/jquery-iu.js' %}"></script>
  <script type="text/javascript" src="{% static 'selectable/js/jquery.dj.selectable.js' %}"></script>

{% endblock %}

source/apps/users/templates/menu.html
{% extends 'dashboardAdministrador.html' %}
{% load static %}

{% block extra_css_nivel %}
  <link href="{% static 'Libs/css/mutual_alta.css' %}" rel="stylesheet" />
{% endblock %}


{% block contenedor %}
<div class="container cuadrado-background">
  <h2 class="text-center titulo">{{ titulo }}</h2>
  <div class="d-grid  mx-auto">
  <br>
 
  <a href="{% url 'users:register_U_M' %}" class="btn btn-outline-primary btn-lg" type="a">
    <i class="fa-solid fa-building-user"></i>
    Usuario Mutual
  </a>

  
  <br>
  <a href="{% url 'users:register_E_P' %}"class="btn btn-outline-primary btn-lg" type="a">
    <i class="fa-regular fa-user"></i>
    Usuario Empleado
  </a>
  
  <br>
  <a href="{% url 'users:register_A' %}" class="btn btn-outline-primary btn-lg" type="a">
    <i class="fa-solid fa-user-shield"></i>
        Usuario Administrador
  </a>
  <br>
</div>

</div>

{% endblock %}

  

source/apps/users/templates/modal_cambiar_contrasenia.html
<div class="modal fade" id="modalpass_{{user.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Cambio de contraseña, usuario: {{user.username}}</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        
        <form id="formulario{{user.pk}}" method="post" action="{% url 'users:cambiar_password_admin' pk=user.id %}">
          {% csrf_token %}
          
          <div class="modal-body">
            <div class="form_group row">
            {% comment %} <label for="inputPassword" class="col-sm-2 col-form-label">Contraseña:</label> {% endcomment %}
              <div class="col-sm-10">
                <input type="password" class="form-control" name="password" id="password" placeholder="ingrese nueva contraseña" required>
              </div>
            </div>
            <br>
          <div class="modal-footer">
            <button type="submit" class="btn btn-outline-success mb-2">Cambiar Contraseña</button>
          </div>
        </form>
          
      </div>
        
      </div>
    </div>
  </div>
<script>
  document.addEventListener('DOMContentLoaded', function() {
  var formulario = document.getElementById('formulario{{user.pk}}');
  formulario.addEventListener('submit', function(event) {
    event.preventDefault(); // Evita que el formulario se envíe normalmente

    // Muestra la ventana de confirmación
    if (confirm('¿Estás seguro que deseas cambiar la conseña de {{user.username}} ?')) {
      formulario.submit(); // Si el usuario confirma, envía el formulario
    }
  });
});
</script>

  
            

source/apps/users/templates/modal_cambiar_estado_user.html
<div class="modal fade" id="cambiarEstado_{{user.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Cambio de Estado, usuario: {{user.username}}</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
               <form id="form{{user.pk}}" method="post" action="{% url 'users:cambiar_estado' pk=user.id %}">
              {% csrf_token %}
              {% if user.is_active %}
              <h6>¿Estas seguro que deseas Dar de baja el usuario: {{user.username}} ?</h6>
              {% else %}           
               <h6>¿Estas seguro que deseas Dar de Alta el usuario: {{user.username}} ?</h6>
              {% endif %}
              
            <div class="modal-footer">
             <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
             <button type="submit" class="btn btn-success">Confirmar</button>
          </a>
            </div>

            </form>
    </div>   
          

        </div>
        
      </div>
    </div>
  </div>


  
            

source/apps/users/templates/modal_detalle_declaracion_presentada.html
<!-- Modal -->
<div class="modal fade" id="modalDeclaracionPresentada_{{declaracion.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            {% for detalle in declaracion.detalles.all %}
            {{ detalle.tipo }} - ${{ detalle.importe }} - {{ detalle.total_registros }} Registros
            <br />

            {% endfor %}        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>

source/apps/users/templates/registrar_usuario_empleado_publico_exito.html
{% extends 'base.html' %}

{% block content %}
  <h2>cliente creado exitosamente</h2>
{% endblock %}

source/apps/users/templates/registrar_usuario_mutual.html
{% extends 'registrar_usuario.html' %}

        {% block registro_mutual %}

        <div class="col-md-6 align-self-end">
          <label for="{{ form.mutual.id_for_label }}" class="form-label">Mutual:</label>
          {{ form.mutual }}
        </div>
        {% endblock %}

source/apps/users/templates/registrar_usuario_mutual_exito.html
{% extends 'base.html' %}

{% block content %}
  <h2>cliente creado exitosamente</h2>
{% endblock %}