source/apps/mutual/urls.py
# Importaciones del sistema
from django.urls import path
from .views import *
app_name = "mutual"

urlpatterns = [
    
    path('crearMutual/',MutualCreateView.as_view(), name="mutual_crear"),
    path('mutuales/listado', MutualesListView.as_view(), name="listado_mutual"),
    path('mutuales/editar/<int:pk>', EditarMutal, name="editar_mutual"),

    path('declaracionjurada/crear/<str:accion>/', DeclaracionJuradaCreateView.as_view(), name="declaracion_jurada"),
    path('declaracionjurada/historialDeclarado',DeclaracionJuradaDeclaradoListView.as_view(), name="declaracion_jurada_declarado_listado"),
    
    path('declaracionjurada/leer',leerDeclaracionJurada , name="leer_declaracion_jurada"),
    path('verificar_todas_leidas/<int:periodo_pk>/', verificar_todas_leidas, name='verificar_declaraciones_todas_leidas'),

    path('declaracionjurada/historico',HistoricoView.as_view(), name="historico"),
    path('DeclaracionJurada/<int:pk>/', descargarDeclaracion, name="descargarDeclaracion"),
    path('DeclaracionJurada/archivo/<int:pk>/', descargarArchivo, name="descargarArchivo"),


    path('periodos/periodo/crear', PeriodoCreateView.as_view(), name="periodo_crear"),
    path('periodos/periodo/vigente', periodoVigenteDetalle , name="periodo_vigente_detalle"),
    path('periodos/periodo/vigente/<int:pk>/mutuales/nopresentaron', periodoVigenteMutualNoPresento , name="mutual_no_presento"),
    path('periodos/periodo/vigente/<int:pk>/finalizar', finalizarPeriodo , name="finalizar_periodo"),
    path('periodos/periodo/vigente/<int:pk>/finalizar_crear_nuevo', finalizarPeriodoCrearNuevo , name="finalizar_periodo_crear_nuevo"),
    
    path('periodos/periodo/<int:pk>/comprimir', comprimirPeriodo, name="comprimir_periodo"),
    
    path('periodos/periodo/descargar', seleccionarPeriodoComprimir, name="comprimir_archivos_periodo"),
    
    
    path('exito/', mutual_exito, name='mutual_exito'),
    path('prueba/', tu_vista, name='t_vista'),
    path('datos/', DetalleMutualView.as_view(), name='detalles_mimutual'),
    path('confirmacion/', ConfirmacionView.as_view(), name='confirmacion'),
    path('visualizar_errores/', VisualizarErroresView.as_view(), name='visualizarE'),
    path('msj_informativo/', MsjInformativo.as_view(), name='msj_info'),

]

source/apps/reportes/urls.py
from django.urls import path

from apps.reportes.views import *

app_name="reportes"


urlpatterns = [
path('reportes/mutual/declaracionesjuradas/<int:mutual_id>/', reporteMutualDeclaracionesJuradasView.as_view(), name="reporte_mutual_declaraciones"),
path('reportes/periodo/',reporte_periodo_dj, name="reporte_periodo"),
]

source/mutualWeb/urls.py
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from mutualWeb.views import *
from .views import *
from mutualWeb import views



urlpatterns = [
    #PRIINCIPALES
    # path('', bienvenida , name='index'),
    path('', RedirectView.as_view(url='login/', permanent=False), name='index'),
    path('admin_manager_ministerio/', admin.site.urls),
    path('dashboard/', dashboard, name='dashboard'),

    #APLICACIONES
    path('dashboard/clientes/', include('apps.clientes.urls')),
    path('dashboard/mutual/', include('apps.mutual.urls')),
    path('dashboard/personas/', include('apps.personas.urls')),
    path('', include('apps.users.urls')),
    path('home/app_reportes/',include('apps.reportes.urls')),

    path("selectable/", include("selectable.urls")),
    path('buscar_mutuales/', views.buscar_mutuales, name='buscar_mutuales'),
    
    # para abir los manuales
    path('manual_usuario_mutual/', abrirManualMutual, name="pdf_manual_mutual"),
    path('manual_usuario_operativos/', abrirManualOperativos, name="pdf_manual_operativos"),
    path('manual_usuario_administrador/', abrirManualAdministrador, name="pdf_manual_administrador"),
]

handler404 = "mutualWeb.views.pagina_no_encontrada"

source/apps/empleadospublicos/models.py
from django.db import models
from ..personas.models import Rol

# Create your models here.
class EmpleadoPublico(Rol):
    TIPO = 3


Rol.register(EmpleadoPublico)

source/apps/empleadospublicos/views.py
from django.shortcuts import render

# Create your views here.

source/apps/empleadospublicos/templates/dashboardEmpleadoPublico.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
  <link href="{% static 'Libs/css/dashboard.css' %}" rel="stylesheet" />
  {% block extra_css_nivel %}

  {% endblock %}
{% endblock %}

{% block content %}
  

  {% include 'navbarEmpleadoPublico.html' %}

  
  
  <div style="display: flex; justify-content: center; align-items: center; min-height: calc(100vh - 60px);">
    {% block contenedor %}
      <div class="cuadrado-background animate__animated animate__fadeIn">
        <h1 class="text-center titulo">¡Bienvenido {{ user }}!</h1>


        <div class="row">
          <div class="col-md-4 col-sm-12">
            <h5>Ultima conexión:</h5>
          </div>
          <div class="col-md-8 col-sm-12">
            <h5 class="negrita">{{ ultimaConexion }}</h5>
          </div>
        </div>
      </div>
    {% endblock %}
  </div>
     
{% endblock %}

source/apps/empleadospublicos/templates/navbarEmpleadoPublico.html
{% extends 'nav_bar.html' %}

{% block opcion_mutual %}
  <li>
    <a class="dropdown-item" href="{% url 'mutual:mutual_crear' %}">Crear</a>
  </li>
  <li>
    <a class="dropdown-item" href="{% url 'mutual:listado_mutual' %}">Listado de Mutuales</a>
  </li>
  {% block opcion_mutual_adicional %}

  {% endblock %}
{% endblock %}

{% block opcion_declaracion_jurada %}
  <li><a class="dropdown-item" href="{% url 'mutual:declaracion_jurada_declarado_listado' %}">Historial de Periodos</a></li>
  <li><a class="dropdown-item" href="{% url 'mutual:periodo_crear' %}">Nuevo Periodo</a></li>
  <li><a class="dropdown-item" href="{% url 'mutual:periodo_vigente_detalle' %}">Periodo Vigente</a></li>
  <li><a class="dropdown-item" href="{% url 'reportes:reporte_periodo' %}">Generar reporte</a></li>
  <li><a class="dropdown-item" href="{% url 'mutual:comprimir_archivos_periodo' %}">Descargar periodo</a></li>

  {% block opcion_declaracion_jurada_adicional %}

  {% endblock %}

{% endblock %}

{% block opcion_ayuda %}
<li>
  <a class="dropdown-item" href="{% url 'pdf_manual_operativos' %}" target="_blank">Manual</a>
</li>
{% endblock %}